# Generated by Django 4.2.29 on 2026-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='branding',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
